name: Run User Defined Script
on:
  workflow_dispatch:
    inputs:
      language:
        description: Programming Language
        type: choice
        options:
          - bash
          - python3
          - node
        required: true
        default: bash
      userinput:
        description: Script User Input
        type: text
        required: false
        
env:
  SCRIPT: ${{ vars.script }}
  LANG: ${{ inputs.language }}
  INPUT: ${{ inputs.userinput }}
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Config
        run: |
    
      - name: Execute Script
        run: |
          echo "$SCRIPT" | tr -d '\r' | bash -
