name: Run User Defined Script
on:
  workflow_dispatch:

permissions:
  contents: write

env:
  SCRIPT: ${{ vars.script }}
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Config
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Execute Script
        run: |
          echo "$SCRIPT" | tr -d '\r' | bash -
