name: Run User Defined Script
run-name: Run User Defined Script

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      SCRIPT: |
        ${{vars.script}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Config
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Convert Line Endings
        run: |
          script_content=$(echo "$SCRIPT" | tr -d '\r')
          echo "$script_content" > script.sh

      - name: Execute Script
        run: |
          bash script.sh
