name: Main Linux Enviornment
run-name: DressedAlarm184 Linux Envirornment

on:
  workflow_dispatch:
    inputs:
      command:
        description: "Execute Command"
        required: true
      variables:
        description: "Custom Variables"
        required: false

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Create user files
        id: createfiles
        run: |
          echo '${{ vars.script }}' | tr -d '\r' > script.sh
          echo '${{ github.actor }}' > user.txt
    
      - name: Run the command
        id: runcommand
        run: |
          IFS=',' read -ra pairs <<< "${{ inputs.variables }}"
          for pair in "${pairs[@]}"; do
              IFS='=' read -r key value <<< "$pair"
              export "$key"="$value"
          done
          ${{ inputs.command }}

      - name: Finalize enviornment
        id: cleanupfinalize
        run: |
          RANDOMINT=$(shuf -i 0-2147483647 -n 1)
          echo "Thank you for using the environment!"
          echo "Here is a random number for you: $RANDOMINT"
      
      - name: Report exit status
        id: reportstatus
        if: always()
        run: echo "Exit status is ${{ steps.runcommand.outcome }}"
