name: Main Linux Enviornment
run-name: DressedAlarm184 Linux Envirornment

on:
  workflow_dispatch:
    inputs:
      command:
        description: "Enter Command"
        required: true
      variables:
        description: "Custom Variables"
        required: false
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Create user files
        run: |
          echo "${{ vars.script }}" | tr -d '\r' > script.sh
          echo "${{ github.actor }}" > user.txt

      - name: Set variables
        run: |
          if [ -n "${{ inputs.variables }}" ]; then
            IFS=',' read -ra VAR_ARRAY <<< "${{ inputs.variables }}"
            for var_pair in "${VAR_ARRAY[@]}"; do
              IFS='=' read -r key value <<< "$var_pair"
              key=$(echo "$key" | tr -d ' ')
              value=$(echo "$value" | tr -d ' ')
              value=$(sed 's/"//g' <<< "$value")
              export "$key"="$value"
            done
          fi
    
      - name: Run command
        run: |
          ${{ inputs.command }}
          export EXITSTATUS = $?
          
      - name: Report exit status
        if: always()
        run: echo -e "Edit status\n$EXITSTATUS"
