name: Main Linux Enviornment
run-name: DressedAlarm184 Linux Envirornment

on:
  workflow_dispatch:
    inputs:
      command:
        description: "Enter Command"
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Create user files
        run: |
          echo "${{ vars.script }}" | tr -d '\r' > script.sh
          echo "${{ github.actor }}" > user.txt
    
      - name: Run command
        run: |
          ${{ inputs.command }}
          
      - name: Report exit status
        if: always()
        run: echo -e "Exit status\n${{ job.steps.1.outcome }}"
