name: Main Linux Enviornment
run-name: DressedAlarm184 Linux Envirornment

on:
  workflow_dispatch:
    inputs:
      command:
        description: "Enter Command"
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Create files
        run: |
          echo "${{ vars.script }}" | tr -d '\r' > script.sh
          echo "${{ github.actor }}" > user.txt
    
      - name: Run command
        run: "${{ inputs.command }}"
