name: Main Linux Enviornment

on:
  workflow_dispatch:
    inputs:
      command:
        description: "Enter Command"
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Create files
        run: |
          echo "${{ vars.script }}" > script.sh
          echo "${{ github.actor }}" > user.txt
    
      - name: Run command
        run: echo "${{ inputs.command }}" | bash
