name: Execute User Command
run-name: Execute User Command

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Enter Command'
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Execute command
        run: ${{ inputs.command }}
