name: Execute User Command
run-name: Execute User Command

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Enter Command'
        required: true
        default: bash script.sh

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Execute command
        run: |
          echo '${{ vars.script }}' | tr -d '\r' > script.sh
          ${{ inputs.command }}
          rm script.sh
