name: Execute User Command
run-name: Execute User Command

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Enter Command'
        required: true

env:
  COMMAND: ${{ inputs.command }}
  SCRIPT: ${{ vars.script }}
  DEFAULT: |
    echo '${{ vars.script }}' | tr -d '\r' > script.sh
    echo '$GITHUB_ACTOR' > user.txt
    $COMMAND

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Execute command
        run: $DEFAULT

