name: Execute User Command

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Enter Command'
        required: true

env:
  SCRIPT: ${{ vars.SCRIPT }}
  USER: ${{ github.actor }}
  COMMAND: ${{ inputs.command }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Create files
        run: |
          echo '$SCRIPT' | tr -d '\r' > script.sh
          echo '$USER' > user.txt

      - name: Execute command
        run: |
          echo '$COMMAND' | bash -
