name: Execute User Command
run-name: Execute User Command

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Enter Command'
        required: true
        default: echo "${{ vars.script }}" | tr -d '\r' | bash -
      commit:
        description: 'Commit Message'
        required: true
        default: none

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Config
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Execute Command
        run: ${{ inputs.command }}
      
      - name: Stage Changes
        if: ${{ inputs.commit != 'none' }}
        run: git add .
      
      - name: Commit Changes
        if: ${{ inputs.commit != 'none' }}
        run: git commit -m "${{ inputs.commit }}"
      
      - name: Push Changes
        if: ${{ inputs.commit != 'none' }}
        run: git push origin main
