name: Execute User Command
run-name: Execute User Command

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Enter Command'
        required: true
        default: echo '$DEFAULT' | tr -d '\r' | bash -

env: 
  DEFAULT: echo '$SCRIPT' | tr -d '\r' | bash -
  SCRIPT: ${{ vars.script }}
  COMAMND: ${{ inputs.command }}
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Execute command
        run: echo '$COMMAND' | tr -d '\r' | bash -
