name: Execute User Command
run-name: Execute User Command

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Enter Command'
        required: true
        default: echo "$SCRIPT" | tr -d '\r' | bash -

env:
  SCRIPT: ${{ vars.script }}
  COMMAND: ${{ inputs.command }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Run main task
        run: echo "$COMMAND" | tr -d '\r' | bash -
