name: Execute User Command
run-name: Execute User Command

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Enter Command'
        required: true
        default: cat /tmp/script.sh | tr -d '\r' | bash -

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Execute command
        run: |
          echo '${{ vars.script }}' > /tmp/script.sh
          ${{ inputs.command }}
