name: Execute User Command
run-name: Execute User Command

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Enter Command'
        required: true
        type: text
        default: echo "$SCRIPT" | tr -d '\r' | bash -
      save:
        description: 'Save Changes'
        required: true
        type: choice
        options:
          - Yes
          - No
        default: No

env:
  SCRIPT: ${{ vars.script }}

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup Config
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Execute Command
        run: ${{ inputs.command }}
      
      - name: Push Changes
        if: ${{ inputs.save == 'Yes' }}
        run: |
          git add .
          git commit -m "Modified repository contents using GitHub Actions"
          git push origin main
